name: 'wiz-cli'
on: [push,pull_request]

jobs:
  wiz-cli-image-scan:
    name: 'Wiz-cli Image Scan'
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "." # Set the relative path in the repo to build the image from
      TAG: "latest" # Set the tag to use for the image
      POLICY: "Default vulnerabilities policy" # Set the desired Wiz CLI policy to use

    # Use the I dont ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download Wiz CLI
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "wgxq75hrlndpbktx3eupevf2x2c4irr4bxuvotfhyukamcqtbtqws" --secret "2CRz8oeUmuZcWyGnMyvvnr1R8KyiQwIc0pvzhH4MZCnapgI9yQXt0f4dAYSESvv4"

